#!/bin/bash
#msg=`echo 'www-data' | sudo -ES /var/www/html/cgi-bin/off.cgi >/dev/null 2>&1`

OFF=0
PIN=0
gpio mode $PIN down
gpio write $PIN $OFF
ecode=$?
echo "Cache-Control: no-cache"
echo "pragma: no-cache"
echo "HTTP/1.0 200 OK"
echo "Content-Type: application/json"
echo "Content-Length: 32"
echo
echo "{\"success\":true, \"exitCode\":\"$ecode\"}"
